### ISSUE TITLE
Merge back into sphinx-apidoc

### ISSUE THREAD

**Issue by wcwoo** [goerz/better-apidoc#12]
I really like your work. Will you continue to work towards incorporating it back to sphinx-apidoc?

**Comment by goerz** [comment]
Probably yes, but it's not a very high priority at the moment. Also, sphinx-apidoc has changed a bit since I forked this, so preparing a patch will be time-consuming.

That being said, I've been using `better-apidoc` in a number of projects, and I'm pretty happy with its current state. So it's really just a matter of finding the time for a pull request.

**Comment by goerz** [comment]
Changes in Sphinx 1.7 and 1.8 have made it impossible to merge this back into Sphinx's `apidoc` (#14). Instead, the plan is now to merge into the [`sphinxcontrib.apidoc` extension](https://github.com/sphinx-contrib/apidoc). This should happen in the relatively near future (at which point `better-apidoc` will become obsolete).
